from __future__ import annotations

import ast
from collections.abc import Callable
from pathlib import Path
import tempfile
from typing import Any

import pytest

from rig_relay.compiler.schema_to_code._ast_safety import check_ast_safety
from rig_relay.compiler.schema_to_code.generator import render_template
from rig_relay.compiler.schema_to_code.reader import (
    ModelSpec,
    _safe_python_identifier,
    derive_model_spec_from_schema,
)


def _call_render_unchecked(*args: Any, **kwargs: Any) -> str:
    f: Callable[..., str] = render_template
    return f(*args, **kwargs)


SCHEMA_DIR = Path(__file__).resolve().parent.parent.parent / "docs" / "schemas"


VALID_IDENTIFIERS = [
    "field_name",
    "snake_case",
    "camelCase",
    "ClassName",
    "_private",
    "x",
    "field_1",
    "schema_version_2",
]

INJECTION_NAMES = ["import", 'print("pwned")']


class TestFieldNameSanitization:
    def test_valid_identifiers_pass(self) -> None:
        for name in VALID_IDENTIFIERS:
            assert _safe_python_identifier(name), f"Valid identifier {name!r} must pass"

    @pytest.mark.parametrize("name", INJECTION_NAMES)
    def test_injection_field_names_are_rejected(self, name: str) -> None:
        assert not _safe_python_identifier(name), (
            f"Injection field name {name!r} must be rejected"
        )

    def test_derive_spec_rejects_hostile_field_name(self) -> None:
        schema = {
            "$id": "test/hostile",
            "properties": {
                "schema_version": {"const": "v1"},
                "1_dangerous_field": {"type": "string"},
            },
            "required": ["schema_version"],
        }
        with pytest.raises(ValueError, match="valid Python identifier"):
            derive_model_spec_from_schema(schema, Path("hostile.json"))


class TestTemplatePathInjection:
    def test_arbitrary_template_path_no_longer_accepted(self) -> None:
        spec = ModelSpec(
            contract_family_id="test", schema_version="v1", imports=[], models=[]
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            hostile_template = Path(tmpdir) / "evil.py.j2"
            hostile_template.write_text("EVIL_INJECTION = True\n")
            with pytest.raises(TypeError):
                _call_render_unchecked(spec, template_path=hostile_template)

    def test_render_template_only_accepts_modelspec(self) -> None:
        with pytest.raises((TypeError, AttributeError)):
            _call_render_unchecked({
                "contract_family_id": "test",
                "schema_version": "v1",
            })


class TestModelSpecDictBypass:
    def test_dict_input_rejected_by_type_check(self) -> None:
        hostile_spec = {
            "contract_family_id": "test",
            "schema_version": "v1",
            "imports": ["from pydantic import BaseModel"],
            "models": [
                {
                    "class_name": "Malicious",
                    "base": "BaseModel",
                    "schema_version": "v1",
                    "fields": [{"name": "field", "type": "str", "optional": False}],
                }
            ],
        }
        with pytest.raises((TypeError, AttributeError)):
            _call_render_unchecked(hostile_spec)

    def test_valid_modelspec_renders_safely(self) -> None:
        spec = ModelSpec(
            contract_family_id="test",
            schema_version="v1",
            imports=["from pydantic import BaseModel"],
            models=[
                {
                    "class_name": "SafeModel",
                    "base": "BaseModel",
                    "schema_version": "v1",
                    "fields": [{"name": "field", "type": "str", "optional": False}],
                }
            ],
        )
        result = render_template(spec)
        assert "class SafeModel" in result
        assert "field: str" in result


DANGEROUS_CODE = (
    "# Generated candidate\n"
    "from __future__ import annotations\n"
    "from pydantic import BaseModel\n"
    "\n"
    "class GeneratedModel(BaseModel):\n"
    '    model_config = {"extra": "forbid"}\n'
    '    schema_version: str = "v1"\n'
    "    field: str\n"
    "\n"
    '__import__("pathlib").Path("/tmp/never_run").write_text("ast-bypass")\n'
)

SAFE_CODE = (
    "# Generated by Contract Compiler Experiment 0\n"
    "from __future__ import annotations\n"
    "from pydantic import BaseModel\n"
    "\n"
    "class GeneratedModel(BaseModel):\n"
    '    model_config = {"extra": "forbid"}\n'
    '    schema_version: str = "v1"\n'
    "    field: str\n"
)


class TestAstSafetyChecker:
    def test_rejects_dangerous_import_call(self) -> None:
        result = check_ast_safety(DANGEROUS_CODE)
        assert not result.safe
        assert any("__import__" in v for v in result.violations)

    def test_accepts_safe_pydantic_model(self) -> None:
        result = check_ast_safety(SAFE_CODE)
        assert result.safe
        assert len(result.violations) == 0

    def test_rejects_eval_call(self) -> None:
        code = safe_code_with_suffix("\neval('1+1')\n")
        result = check_ast_safety(code)
        assert not result.safe
        assert any("eval" in v for v in result.violations)

    def test_rejects_exec_call(self) -> None:
        code = safe_code_with_suffix('\nexec("x=1")\n')
        result = check_ast_safety(code)
        assert not result.safe
        assert any("exec" in v for v in result.violations)

    def test_rejects_os_system_call(self) -> None:
        code = safe_code_with_suffix("\nimport os\nos.system('echo pwned')\n")
        result = check_ast_safety(code)
        assert not result.safe

    def test_rejects_compile_call(self) -> None:
        code = safe_code_with_suffix('\ncompile("x=1", "<string>", "exec")\n')
        result = check_ast_safety(code)
        assert not result.safe
        assert any("compile" in v for v in result.violations)

    def test_rejects_open_call(self) -> None:
        code = safe_code_with_suffix('\nopen("/etc/passwd").read()\n')
        result = check_ast_safety(code)
        assert not result.safe
        assert any("open" in v for v in result.violations)

    def test_rejects_subprocess_import(self) -> None:
        code = safe_code_with_suffix("\nimport subprocess\n")
        result = check_ast_safety(code)
        assert not result.safe
        assert any("subprocess" in v for v in result.violations)

    def test_rejects_ctypes_kernel32(self) -> None:
        code = safe_code_with_suffix("\nimport ctypes\n")
        result = check_ast_safety(code)
        assert not result.safe
        assert any("ctypes" in v for v in result.violations)

    def test_rejects_socket_import(self) -> None:
        code = safe_code_with_suffix("\nimport socket\n")
        result = check_ast_safety(code)
        assert not result.safe
        assert any("socket" in v for v in result.violations)

    def test_rejects_breakpoint_call(self) -> None:
        code = safe_code_with_suffix("\nbreakpoint()\n")
        result = check_ast_safety(code)
        assert not result.safe
        assert any("breakpoint" in v for v in result.violations)

    def test_ast_parse_reveals_dangerous_nodes(self) -> None:
        tree = ast.parse(DANGEROUS_CODE)
        dangerous = [
            node
            for node in ast.walk(tree)
            if isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "__import__"
        ]
        assert len(dangerous) > 0, "AST must detect __import__() calls"

    def test_ast_allowlist_rejects_unauthorized_calls(self) -> None:
        result = check_ast_safety(DANGEROUS_CODE)
        assert not result.safe
        assert result.violations, (
            "AST gate must detect dangerous calls in generated code"
        )


class TestValidationBypass:
    def test_run_validation_false_still_runs_minimum_safety(self) -> None:
        from rig_relay.compiler.schema_to_code.compiler import compile_schema_to_code

        schema_path = (
            SCHEMA_DIR / "rig.relay.coordination.fake_green_event.v1.schema.json"
        )
        if not schema_path.exists():
            pytest.skip(f"Test schema not found at {schema_path}")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "output"
            result = compile_schema_to_code(
                schema_path=schema_path, output_dir=output_dir, run_validation=False
            )
            gate_matrix = result.get("gate_matrix", {})
            gates = gate_matrix.get("gates", [])
            assert len(gates) >= 2, (
                f"run_validation=False must still run minimum safety gates "
                f"(schema+ast). Got {len(gates)} gates."
            )


def safe_code_with_suffix(suffix: str) -> str:
    return SAFE_CODE + suffix
