from __future__ import annotations

import json

from pydantic import ValidationError
import pytest

from vibe.core.config import VibeConfig
from vibe.core.relay import GitSafetyPolicy, RelayReceiptMetadata, SkillManifest


def test_vibe_config_defaults_for_rig_relay():
    config = VibeConfig()
    assert config.active_model == "deepseek-v4-flash"
    assert config.enable_telemetry is False
    assert config.include_commit_signature is False
    assert config.enable_update_checks is False
    assert config.enable_auto_update is False
    assert config.enable_notifications is False
    assert config.autocopy_to_clipboard is False

    # Check providers
    provider_names = [p.name for p in config.providers]
    assert "deepseek" in provider_names

    deepseek = next(p for p in config.providers if p.name == "deepseek")
    assert deepseek.api_base == "https://api.deepseek.com"
    assert deepseek.api_key_env_var == "DEEPSEEK_API_KEY"


def test_git_safety_policy():
    policy = GitSafetyPolicy()
    assert "git reset" in policy.forbidden_commands
    assert "git reset --hard" in policy.forbidden_commands
    assert "git clean" in policy.forbidden_commands
    assert "git rebase" in policy.forbidden_commands
    assert policy.commit_requires_user_request is True


def test_relay_receipt_metadata_serialization():
    receipt = RelayReceiptMetadata(
        selected_model="deepseek-v4-flash",
        selected_provider="deepseek",
        result_status="success",
        changed_files=["file1.py", "file2.py"],
    )
    data = receipt.model_dump_json()
    parsed = json.loads(data)
    assert parsed["harness_name"] == "rig-relay"
    assert parsed["selected_model"] == "deepseek-v4-flash"
    assert parsed["result_status"] == "success"


def test_skill_manifest_validation():
    # Valid manifest
    manifest = SkillManifest(
        id="test-skill", title="Test Skill", description="A test skill"
    )
    assert manifest.id == "test-skill"

    # Invalid manifest (missing required field)
    with pytest.raises(ValidationError):
        SkillManifest(id="test")


def test_system_prompt_branding_neutrality():
    config = VibeConfig()
    # Mocking dependencies for get_universal_system_prompt would be complex here,
    # but we can check the individual prompt files.
    prompt = config.system_prompt
    assert "Rig Relay" in prompt
    assert "Mistral Vibe" not in prompt
    assert "Generated by Mistral" not in prompt
    assert "Co-Authored-By" not in prompt
