"""Distribution & Release Governance Research — static data for artifact generation."""

from __future__ import annotations

CHANNELS = [
    {"channel_id": "dist-channel:apple_app_store", "channel_family": "apple_app_store", "ecosystem": "apple", "official_docs_refs": ["https://developer.apple.com/app-store-connect/api/"], "developer_value": "Primary macOS/iOS distribution surface", "risk_level": "high"},
    {"channel_id": "dist-channel:apple_testflight", "channel_family": "apple_testflight", "ecosystem": "apple", "developer_value": "Beta distribution to testers before App Store", "risk_level": "medium"},
    {"channel_id": "dist-channel:apple_notarization", "channel_family": "apple_macos_notarization", "ecosystem": "apple", "developer_value": "Gatekeeper trust for macOS apps outside App Store", "risk_level": "medium"},
    {"channel_id": "dist-channel:apple_dev_id_distribution", "channel_family": "apple_developer_id_direct_distribution", "ecosystem": "apple", "developer_value": "Direct macOS distribution (website, third-party stores)", "risk_level": "medium"},
    {"channel_id": "dist-channel:google_play_production", "channel_family": "google_play_production", "ecosystem": "google", "developer_value": "Primary Android distribution to billions of devices", "risk_level": "high"},
    {"channel_id": "dist-channel:google_play_internal", "channel_family": "google_play_internal_testing", "ecosystem": "google", "developer_value": "Quick internal distribution (up to 100 testers)", "risk_level": "low"},
    {"channel_id": "dist-channel:google_play_closed", "channel_family": "google_play_closed_testing", "ecosystem": "google", "developer_value": "Alpha testing to trusted groups", "risk_level": "low"},
    {"channel_id": "dist-channel:google_play_open", "channel_family": "google_play_open_testing", "ecosystem": "google", "developer_value": "Public beta testing on Play Store", "risk_level": "medium"},
    {"channel_id": "dist-channel:microsoft_store", "channel_family": "microsoft_store", "ecosystem": "microsoft", "developer_value": "Windows desktop distribution via Microsoft Store", "risk_level": "high"},
    {"channel_id": "dist-channel:microsoft_partner_center", "channel_family": "microsoft_partner_center_marketplace", "ecosystem": "microsoft", "developer_value": "Azure Marketplace distribution", "risk_level": "high"},
    {"channel_id": "dist-channel:github_releases", "channel_family": "github_releases", "ecosystem": "github", "developer_value": "Primary OSS release distribution with assets", "risk_level": "medium"},
    {"channel_id": "dist-channel:github_pages", "channel_family": "github_pages", "ecosystem": "github", "developer_value": "Static site hosting for docs and changelogs", "risk_level": "low"},
    {"channel_id": "dist-channel:npm_registry", "channel_family": "npm_registry", "ecosystem": "javascript", "developer_value": "Primary JavaScript package registry", "risk_level": "high"},
    {"channel_id": "dist-channel:bun_publish", "channel_family": "bun_publish_npm_registry", "ecosystem": "javascript", "developer_value": "Bun-native npm-compatible publishing", "risk_level": "high"},
    {"channel_id": "dist-channel:pypi", "channel_family": "pypi", "ecosystem": "python", "developer_value": "Python Package Index", "risk_level": "high"},
    {"channel_id": "dist-channel:testpypi", "channel_family": "testpypi", "ecosystem": "python", "developer_value": "Pre-production PyPI testing", "risk_level": "low"},
    {"channel_id": "dist-channel:crates_io", "channel_family": "crates_io", "ecosystem": "rust", "developer_value": "Rust crate registry", "risk_level": "high"},
    {"channel_id": "dist-channel:docs_rs", "channel_family": "docs_rs", "ecosystem": "rust", "developer_value": "Automatic Rust documentation hosting", "risk_level": "low"},
    {"channel_id": "dist-channel:homebrew_formula", "channel_family": "homebrew_formula", "ecosystem": "homebrew", "developer_value": "macOS/Linux package manager distribution", "risk_level": "medium"},
    {"channel_id": "dist-channel:homebrew_cask", "channel_family": "homebrew_cask", "ecosystem": "homebrew", "developer_value": "GUI macOS application distribution via Homebrew", "risk_level": "medium"},
    {"channel_id": "dist-channel:private_homebrew_tap", "channel_family": "private_homebrew_tap", "ecosystem": "homebrew", "developer_value": "Private/internal Homebrew distribution", "risk_level": "low"},
    {"channel_id": "dist-channel:ghcr", "channel_family": "github_container_registry", "ecosystem": "containers", "developer_value": "GitHub-hosted OCI container registry", "risk_level": "medium"},
    {"channel_id": "dist-channel:docker_hub", "channel_family": "docker_hub", "ecosystem": "containers", "developer_value": "Primary public container image registry", "risk_level": "medium"},
    {"channel_id": "dist-channel:generic_oci", "channel_family": "generic_oci_registry", "ecosystem": "containers", "developer_value": "Any OCI-compliant registry (ECR, GCR, ACR, etc.)", "risk_level": "medium"},
    {"channel_id": "dist-channel:direct_download", "channel_family": "direct_download_static_site", "ecosystem": "direct", "developer_value": "Direct download from project website/CDN", "risk_level": "medium"},
    {"channel_id": "dist-channel:enterprise_internal", "channel_family": "enterprise_internal_distribution", "ecosystem": "enterprise", "developer_value": "Enterprise distribution via MDM, private stores", "risk_level": "medium"},
    {"channel_id": "dist-channel:self_update", "channel_family": "self_update_channel", "ecosystem": "direct", "developer_value": "In-app auto-update (Sparkle, Squirrel, electron-updater)", "risk_level": "medium"},
]

CREDENTIALS = [
    {"credential_id": "dist-cred:apple_connect_api_key", "channel_ids": ["dist-channel:apple_app_store", "dist-channel:apple_testflight"], "purpose": "App Store Connect API authentication", "storage_sensitivity": "critical", "redaction_requirements": "Never log private key. Hash key_id for evidence.", "recommended_rig_handling": "Store encrypted. Use via Rig credential manager.", "compromise_impact": "Attacker can upload builds, manage TestFlight.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:apple_dev_cert", "channel_ids": ["dist-channel:apple_app_store", "dist-channel:apple_testflight", "dist-channel:apple_notarization", "dist-channel:apple_dev_id_distribution"], "purpose": "Code signing for development and distribution", "storage_sensitivity": "critical", "redaction_requirements": "Never log private key. Log certificate SHA1 fingerprint only.", "recommended_rig_handling": "Store in macOS Keychain or CI vault. Monitor expiration.", "compromise_impact": "Attacker can sign malware as your identity.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:apple_provisioning", "channel_ids": ["dist-channel:apple_app_store", "dist-channel:apple_testflight", "dist-channel:apple_notarization"], "purpose": "Links app ID, certificate, and entitlements", "storage_sensitivity": "high", "redaction_requirements": "Store profile. Hash profile UUID for evidence.", "recommended_rig_handling": "Store as build artifact. Validate before signing.", "compromise_impact": "Lower than certificate. Allows unauthorized device enrollment.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:apple_notary_api_key", "channel_ids": ["dist-channel:apple_notarization"], "purpose": "Notarization via App Store Connect API key", "storage_sensitivity": "critical", "redaction_requirements": "Never log private key. Hash key_id.", "recommended_rig_handling": "API key stored in keychain. notarytool --keychain-profile.", "compromise_impact": "Attacker can submit malware for notarization.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:google_service_account", "channel_ids": ["dist-channel:google_play_production", "dist-channel:google_play_internal", "dist-channel:google_play_closed", "dist-channel:google_play_open"], "purpose": "Google Play Developer API access", "storage_sensitivity": "critical", "redaction_requirements": "Never log JSON key file contents. Hash service account email.", "recommended_rig_handling": "Minimal scopes. Service account per pipeline. Store in secure vault.", "compromise_impact": "Catastrophic — attacker can publish any app under developer account.", "remaining_unknowns": "Play Console role granularity for API-only access."},
    {"credential_id": "dist-cred:google_upload_key", "channel_ids": ["dist-channel:google_play_production", "dist-channel:google_play_internal", "dist-channel:google_play_closed", "dist-channel:google_play_open"], "purpose": "Signs AAB/APK for upload to Play Console", "storage_sensitivity": "critical", "redaction_requirements": "Never log keystore password or private key. Log key fingerprint SHA256.", "recommended_rig_handling": "Store in CI secrets. Back up securely.", "compromise_impact": "Attacker can upload builds.", "remaining_unknowns": "Google support response time for key reset."},
    {"credential_id": "dist-cred:msft_partner_center", "channel_ids": ["dist-channel:microsoft_store", "dist-channel:microsoft_partner_center"], "purpose": "Partner Center API access for Store submissions", "storage_sensitivity": "critical", "redaction_requirements": "Never log client secret. Hash tenant_id+client_id.", "recommended_rig_handling": "Azure Key Vault or CI vault. Rotate regularly.", "compromise_impact": "Attacker can manage app submissions, update listings.", "remaining_unknowns": "Exact Azure AD permission set for Store-only access."},
    {"credential_id": "dist-cred:msft_code_signing", "channel_ids": ["dist-channel:microsoft_store", "dist-channel:direct_download"], "purpose": "Code signing certificate for Windows binaries and MSIX", "storage_sensitivity": "critical", "redaction_requirements": "Never log private key. Log certificate thumbprint.", "recommended_rig_handling": "HSM if possible. CI vault minimum. Monitor expiration.", "compromise_impact": "Attacker can sign malware as your identity.", "remaining_unknowns": "EV vs standard certificate SmartScreen behavior."},
    {"credential_id": "dist-cred:npm_token", "channel_ids": ["dist-channel:npm_registry", "dist-channel:bun_publish"], "purpose": "Publish packages to npm registry", "storage_sensitivity": "critical", "redaction_requirements": "Never log token. Hash token prefix for evidence.", "recommended_rig_handling": "Granular tokens with minimal scope. 2FA required. Prefer OIDC.", "compromise_impact": "Attacker can publish malicious versions of packages.", "remaining_unknowns": "Classic token deprecation timeline."},
    {"credential_id": "dist-cred:npm_oidc", "channel_ids": ["dist-channel:npm_registry", "dist-channel:bun_publish"], "purpose": "Passwordless npm publishing via OIDC trusted publishers", "storage_sensitivity": "none", "redaction_requirements": "No token to redact. Provenance attestation is content-light.", "recommended_rig_handling": "Preferred over tokens. Use in CI.", "compromise_impact": "Attacker with repo write access can publish. No credential to steal.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:pypi_token", "channel_ids": ["dist-channel:pypi", "dist-channel:testpypi"], "purpose": "Publish Python packages to PyPI", "storage_sensitivity": "critical", "redaction_requirements": "Never log token. Hash token prefix for evidence.", "recommended_rig_handling": "Project-scoped tokens. Prefer Trusted Publishers (OIDC).", "compromise_impact": "Attacker can publish malicious packages under your name.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:pypi_oidc", "channel_ids": ["dist-channel:pypi", "dist-channel:testpypi"], "purpose": "Passwordless PyPI publishing via OIDC trusted publishers", "storage_sensitivity": "none", "redaction_requirements": "No token. Attestation is content-light.", "recommended_rig_handling": "Preferred over API tokens.", "compromise_impact": "Repo write access allows publish. No credential to exfiltrate.", "remaining_unknowns": "PEP 740 digital attestation integration timeline."},
    {"credential_id": "dist-cred:crates_token", "channel_ids": ["dist-channel:crates_io"], "purpose": "Publish Rust crates to crates.io", "storage_sensitivity": "critical", "redaction_requirements": "Never log token. Hash token for evidence.", "recommended_rig_handling": "Use publish-update scope. Store in CI secrets.", "compromise_impact": "Catastrophic — publishes permanent crate versions.", "remaining_unknowns": "crates.io OIDC trusted publishing timeline."},
    {"credential_id": "dist-cred:homebrew_github_token", "channel_ids": ["dist-channel:homebrew_formula", "dist-channel:homebrew_cask", "dist-channel:private_homebrew_tap"], "purpose": "GitHub access for tap repo push, PR creation, bottle upload", "storage_sensitivity": "high", "redaction_requirements": "Never log token. Hash token prefix for evidence.", "recommended_rig_handling": "Fine-grained PAT or GitHub App. Minimal scope.", "compromise_impact": "Repo write access. Attacker can modify formula/cask.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:github_release_token", "channel_ids": ["dist-channel:github_releases"], "purpose": "Create GitHub Releases and upload assets", "storage_sensitivity": "high", "redaction_requirements": "Never log token. Use GITHUB_TOKEN in CI (ephemeral). Hash for evidence.", "recommended_rig_handling": "Use GITHUB_TOKEN where possible. Fine-grained PAT otherwise.", "compromise_impact": "Attacker can create releases, modify tags.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:github_pages_token", "channel_ids": ["dist-channel:github_pages"], "purpose": "Deploy to GitHub Pages", "storage_sensitivity": "high", "redaction_requirements": "Same as GitHub release token.", "recommended_rig_handling": "Use GITHUB_TOKEN.", "compromise_impact": "Defacement of GitHub Pages site.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:container_registry_token", "channel_ids": ["dist-channel:ghcr", "dist-channel:docker_hub", "dist-channel:generic_oci"], "purpose": "Push/pull container images to registry", "storage_sensitivity": "high", "redaction_requirements": "Never log token. Hash for evidence.", "recommended_rig_handling": "Read-only tokens for pull. Publish tokens with minimal scope.", "compromise_impact": "Attacker can push malicious images.", "remaining_unknowns": "Registry-specific OIDC support levels."},
    {"credential_id": "dist-cred:cosign_key", "channel_ids": ["dist-channel:ghcr", "dist-channel:docker_hub", "dist-channel:generic_oci"], "purpose": "Sign container images and attestations with cosign", "storage_sensitivity": "critical", "redaction_requirements": "Never log private key. Never commit cosign.key.", "recommended_rig_handling": "Prefer keyless (OIDC). If using key, store in KMS/HSM.", "compromise_impact": "Attacker can sign malicious images as your identity.", "remaining_unknowns": "Cosign keyless OIDC provider coverage."},
    {"credential_id": "dist-cred:gpg_key", "channel_ids": ["dist-channel:github_releases", "dist-channel:direct_download"], "purpose": "Sign git tags, release artifacts with GPG", "storage_sensitivity": "critical", "redaction_requirements": "Never log private key. Log key fingerprint.", "recommended_rig_handling": "Use hardware token (YubiKey). CI: use SSH signing or GitHub's own.", "compromise_impact": "Trust anchor broken. All signatures become suspect.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:ssh_key", "channel_ids": ["dist-channel:github_releases", "dist-channel:github_pages", "dist-channel:homebrew_formula", "dist-channel:homebrew_cask", "dist-channel:private_homebrew_tap"], "purpose": "Git operations via SSH. Tag signing.", "storage_sensitivity": "high", "redaction_requirements": "Never log private key. Log public key fingerprint.", "recommended_rig_handling": "Deploy keys with read-only or write per repo.", "compromise_impact": "Attacker can push commits, modify releases.", "remaining_unknowns": "None."},
    {"credential_id": "dist-cred:sigstore_oidc", "channel_ids": ["dist-channel:ghcr", "dist-channel:docker_hub", "dist-channel:generic_oci", "dist-channel:npm_registry", "dist-channel:pypi"], "purpose": "Keyless signing via OIDC identity (Sigstore/Fulcio/Rekor)", "storage_sensitivity": "none", "redaction_requirements": "No key. OIDC token is ephemeral.", "recommended_rig_handling": "Preferred signing model. Use in CI. No key management.", "compromise_impact": "Attacker with workflow access can sign. No long-lived credential.", "remaining_unknowns": "None."},
]

APIS = [
    {"surface_id": "dist-api:app_store_connect", "vendor": "apple", "channel_ids": ["dist-channel:apple_app_store", "dist-channel:apple_testflight"], "auth_model": "JWT signed with App Store Connect API key (ES256)", "best_auth_boundary_for_rig": "API key + JWT, stored encrypted", "supported_reads": ["apps", "builds", "beta_groups", "review_submissions", "sales_reports"], "supported_writes": ["submit_for_review", "beta_tester_invitations", "beta_group_assignments", "metadata_updates"], "rate_limits_or_quota_notes": "3600 req/hour (sandbox), 7200 req/hour (production)", "test_strategy": "Read-only: list apps/builds.", "remaining_unknowns": "App Review submission API stability."},
    {"surface_id": "dist-api:apple_notary_api", "vendor": "apple", "channel_ids": ["dist-channel:apple_notarization"], "auth_model": "JWT signed with App Store Connect API key", "best_auth_boundary_for_rig": "API key. No app-specific passwords.", "supported_reads": ["notarization_status", "notarization_log"], "supported_writes": ["submit_for_notarization"], "rate_limits_or_quota_notes": "75 uploads per hour (standard limit)", "test_strategy": "Submit known-good signed DMG. Check status.", "remaining_unknowns": "None."},
    {"surface_id": "dist-api:notarytool", "vendor": "apple", "channel_ids": ["dist-channel:apple_notarization", "dist-channel:apple_dev_id_distribution"], "auth_model": "App Store Connect API key or app-specific password", "best_auth_boundary_for_rig": "API key stored in keychain (notarytool --keychain-profile)", "supported_reads": ["notarytool history", "notarytool info", "notarytool log"], "supported_writes": ["notarytool submit", "notarytool notarize (auto-wait)"], "rate_limits_or_quota_notes": "Same as Notary API", "test_strategy": "notarytool submit dry-run.", "remaining_unknowns": "None."},
    {"surface_id": "dist-api:google_play", "vendor": "google", "channel_ids": ["dist-channel:google_play_production", "dist-channel:google_play_internal", "dist-channel:google_play_closed", "dist-channel:google_play_open"], "auth_model": "Service account JSON key + OAuth 2.0 (JWT bearer)", "best_auth_boundary_for_rig": "Service account with minimal role. Separate per-pipeline accounts.", "supported_reads": ["edits", "tracks", "listings", "reviews", "stats"], "supported_writes": ["create_edit", "upload_bundle", "update_track", "commit_edit"], "rate_limits_or_quota_notes": "200,000 queries per day", "test_strategy": "Create edit, upload, assign internal track, DO NOT COMMIT, discard edit.", "remaining_unknowns": "Edits API deprecation timeline."},
    {"surface_id": "dist-api:msft_store", "vendor": "microsoft", "channel_ids": ["dist-channel:microsoft_store", "dist-channel:microsoft_partner_center"], "auth_model": "Azure AD app registration + client credentials", "best_auth_boundary_for_rig": "Azure AD app with minimal Partner Center permissions.", "supported_reads": ["submissions", "app_listings", "flight_submissions", "analytics"], "supported_writes": ["create_submission", "update_submission", "commit_submission"], "rate_limits_or_quota_notes": "60 req/min, 5000 req/day", "test_strategy": "Read submissions, create draft, DO NOT COMMIT, delete draft.", "remaining_unknowns": "Azure AD auth model evolution toward MS Graph."},
    {"surface_id": "dist-api:gh_releases", "vendor": "github", "channel_ids": ["dist-channel:github_releases"], "auth_model": "GitHub App installation token or fine-grained PAT", "best_auth_boundary_for_rig": "GitHub App installation token. Fine-grained PAT as fallback.", "supported_reads": ["releases", "release_assets"], "supported_writes": ["create_release", "update_release", "upload_asset"], "rate_limits_or_quota_notes": "5000 req/hour", "test_strategy": "Create draft release, validate, delete draft.", "remaining_unknowns": "GitHub Attestations API (beta) integration."},
    {"surface_id": "dist-api:npm_publish", "vendor": "npm", "channel_ids": ["dist-channel:npm_registry", "dist-channel:bun_publish"], "auth_model": "npm access token (Bearer). OIDC for trusted publishing.", "best_auth_boundary_for_rig": "Granular token (publish scope for specific package). OIDC preferred.", "supported_reads": ["npm view", "npm info", "npm search"], "supported_writes": ["npm publish", "npm deprecate", "npm dist-tag"], "rate_limits_or_quota_notes": "Reasonable. Per IP/token.", "test_strategy": "npm publish --dry-run. Publish to private registry for integration test.", "remaining_unknowns": "Classic token phase-out timeline."},
    {"surface_id": "dist-api:twine", "vendor": "pypa", "channel_ids": ["dist-channel:pypi", "dist-channel:testpypi"], "auth_model": "PyPI API token or Trusted Publisher (OIDC)", "best_auth_boundary_for_rig": "Project-scoped PyPI token. Trusted Publisher preferred.", "supported_reads": [], "supported_writes": ["twine upload"], "rate_limits_or_quota_notes": "Generous. Not publicly documented per-endpoint.", "test_strategy": "twine check. twine upload --repository testpypi.", "remaining_unknowns": "uv publish replacing twine timeline."},
    {"surface_id": "dist-api:cargo_publish", "vendor": "rust", "channel_ids": ["dist-channel:crates_io"], "auth_model": "crates.io API token via cargo login", "best_auth_boundary_for_rig": "publish-update token for existing crates. Minimal scope.", "supported_reads": ["cargo search"], "supported_writes": ["cargo publish", "cargo yank", "cargo unyank"], "rate_limits_or_quota_notes": "1 new crate per 5 minutes. Updates less restrictive.", "test_strategy": "cargo publish --dry-run. cargo package.", "remaining_unknowns": "crates.io OIDC support."},
    {"surface_id": "dist-api:homebrew", "vendor": "homebrew", "channel_ids": ["dist-channel:homebrew_formula", "dist-channel:homebrew_cask", "dist-channel:private_homebrew_tap"], "auth_model": "GitHub token or SSH", "best_auth_boundary_for_rig": "GitHub App token for tap. Fork + PR for homebrew/core.", "supported_reads": ["brew audit", "brew info", "brew search"], "supported_writes": ["brew create", "brew bump-formula-pr"], "rate_limits_or_quota_notes": "GitHub rate limits apply.", "test_strategy": "brew audit, brew test. Push to private tap first.", "remaining_unknowns": "Homebrew core maintainer review timeline."},
]

VALIDATIONS = [
    {"validation_id": "dist-valid:build_reproducibility", "applies_to_channels": ["*"], "pass_condition": "Identical hashes from independent builds", "can_block_publish": True, "recommended_default_severity": "warning"},
    {"validation_id": "dist-valid:artifact_hashing", "applies_to_channels": ["*"], "pass_condition": "SHA256 computed and stored", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:semver_check", "applies_to_channels": ["*"], "pass_condition": "Version > previous AND valid semver", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:changelog_check", "applies_to_channels": ["*"], "pass_condition": "Current version appears in changelog", "can_block_publish": False, "recommended_default_severity": "warning"},
    {"validation_id": "dist-valid:release_notes_check", "applies_to_channels": ["*"], "pass_condition": "Release notes present and valid", "can_block_publish": False, "recommended_default_severity": "warning"},
    {"validation_id": "dist-valid:license_check", "applies_to_channels": ["*"], "pass_condition": "Valid LICENSE file present", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:provenance_check", "applies_to_channels": ["dist-channel:npm_registry", "dist-channel:pypi", "dist-channel:ghcr"], "pass_condition": "Attestation verifies against package hash", "can_block_publish": False, "recommended_default_severity": "warning"},
    {"validation_id": "dist-valid:sbom_check", "applies_to_channels": ["dist-channel:ghcr", "dist-channel:docker_hub", "dist-channel:generic_oci"], "pass_condition": "SBOM valid and includes all dependencies", "can_block_publish": False, "recommended_default_severity": "warning"},
    {"validation_id": "dist-valid:vulnerability_scan", "applies_to_channels": ["dist-channel:ghcr", "dist-channel:docker_hub"], "pass_condition": "No critical/high CVE in image", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:secret_scan", "applies_to_channels": ["*"], "pass_condition": "No secrets detected in source/artifacts", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:dependency_audit", "applies_to_channels": ["dist-channel:npm_registry", "dist-channel:pypi", "dist-channel:crates_io"], "pass_condition": "No known vulnerabilities in dependencies", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:test_result", "applies_to_channels": ["*"], "pass_condition": "All tests pass", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:schema_validation", "applies_to_channels": ["*"], "pass_condition": "Data validates against schema", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:code_signing", "applies_to_channels": ["dist-channel:apple_app_store", "dist-channel:apple_notarization", "dist-channel:apple_dev_id_distribution", "dist-channel:microsoft_store"], "pass_condition": "Valid signature with trusted certificate", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:notarization", "applies_to_channels": ["dist-channel:apple_notarization", "dist-channel:apple_dev_id_distribution"], "pass_condition": "Notarization ticket present and valid", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:entitlement", "applies_to_channels": ["dist-channel:apple_app_store", "dist-channel:apple_testflight"], "pass_condition": "Entitlements match provisioning profile", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:provisioning_profile", "applies_to_channels": ["dist-channel:apple_app_store", "dist-channel:apple_testflight"], "pass_condition": "Profile valid, not expired, matches certificate", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:package_metadata", "applies_to_channels": ["dist-channel:npm_registry", "dist-channel:pypi", "dist-channel:crates_io"], "pass_condition": "All required metadata fields present and valid", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:package_file_manifest", "applies_to_channels": ["dist-channel:npm_registry", "dist-channel:pypi", "dist-channel:crates_io"], "pass_condition": "Expected files present, no unexpected files", "can_block_publish": False, "recommended_default_severity": "warning"},
    {"validation_id": "dist-valid:store_metadata", "applies_to_channels": ["dist-channel:apple_app_store", "dist-channel:google_play_production", "dist-channel:microsoft_store"], "pass_condition": "All required store listing fields present", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:privacy_manifest", "applies_to_channels": ["dist-channel:apple_app_store"], "pass_condition": "Privacy manifest present and valid", "can_block_publish": True, "recommended_default_severity": "error"},
    {"validation_id": "dist-valid:public_claims", "applies_to_channels": ["*"], "pass_condition": "All public claims consistent across surfaces", "can_block_publish": False, "recommended_default_severity": "warning"},
]

MUTATIONS = [
    {"mutation_lane_id": "dist-mut:create_release_packet", "channel_ids": ["dist-channel:github_releases"], "recommended_initial_state": "approval_required", "remote_mutation": True, "local_mutation": False, "reason": "Public mutation. Tag is permanent signal."},
    {"mutation_lane_id": "dist-mut:create_store_submission", "channel_ids": ["dist-channel:apple_app_store"], "recommended_initial_state": "approval_required", "remote_mutation": True, "local_mutation": False, "reason": "Human review triggered. Rejection is public record."},
    {"mutation_lane_id": "dist-mut:npm_publish", "channel_ids": ["dist-channel:npm_registry"], "recommended_initial_state": "approval_required", "remote_mutation": True, "local_mutation": False, "reason": "Public registry mutation. Version permanent.", "dangerous_failure_modes": ["Wrong version published.", "Private data leaked in package.", "Version number permanently reserved."], "rollback_or_recovery_strategy": "npm unpublish (within 72h). npm deprecate. Dist-tag redirect.", "receipts_required": ["package_name", "version", "tar_sha", "publish_timestamp"]},
    {"mutation_lane_id": "dist-mut:pypi_upload", "channel_ids": ["dist-channel:pypi"], "recommended_initial_state": "approval_required", "remote_mutation": True, "local_mutation": False, "reason": "Irreversible registry mutation. Version is permanent.", "dangerous_failure_modes": ["Wrong version published.", "Files cannot be modified after upload.", "Version number permanently reserved."], "rollback_or_recovery_strategy": "PyPI yank (soft). Delete within 72h.", "receipts_required": ["package_name", "version", "wheel_hash", "upload_timestamp"]},
    {"mutation_lane_id": "dist-mut:crates_publish", "channel_ids": ["dist-channel:crates_io"], "recommended_initial_state": "approval_required", "remote_mutation": True, "local_mutation": False, "reason": "Permanent registry mutation. No OIDC keyless yet.", "dangerous_failure_modes": ["Wrong version published.", "Cannot be deleted.", "Crate name permanently reserved."], "rollback_or_recovery_strategy": "cargo yank. Crate version cannot be deleted."},
    {"mutation_lane_id": "dist-mut:create_github_release", "channel_ids": ["dist-channel:github_releases"], "recommended_initial_state": "approval_required", "remote_mutation": True, "local_mutation": False, "reason": "Public notification. Tag namespace is permanent signal.", "rollback_or_recovery_strategy": "Delete release, delete tag (notifications already sent)."},
    {"mutation_lane_id": "dist-mut:generate_sbom", "channel_ids": ["dist-channel:ghcr", "dist-channel:docker_hub", "dist-channel:generic_oci", "dist-channel:github_releases"], "recommended_initial_state": "automatic_under_policy", "remote_mutation": False, "local_mutation": True, "reason": "Read-only generation. No remote mutation."},
    {"mutation_lane_id": "dist-mut:notarize_macos", "channel_ids": ["dist-channel:apple_notarization"], "recommended_initial_state": "approval_required", "remote_mutation": True, "local_mutation": True, "reason": "Remote notarization service call. Local signing prep.", "rollback_or_recovery_strategy": "Notarization submission can be deleted."},
    {"mutation_lane_id": "dist-mut:sign_artifact", "channel_ids": ["dist-channel:direct_download", "dist-channel:self_update"], "recommended_initial_state": "automatic_under_policy", "remote_mutation": False, "local_mutation": True, "reason": "Local signing only. Must have certificate access.", "dangerous_failure_modes": ["Wrong cert used.", "Expired cert not caught.", "Private key exposure in CI logs."]},
]

RISKS = [
    {"risk_id": "dist-risk:credential_leakage", "category": "security", "affected_channels": ["*"], "severity": "critical", "likelihood": "medium", "description": "Distribution credentials leaked via logs, version control, CI output, or artifact metadata.", "mitigation": "Secret scanning in CI. Never log raw credentials. Hash credential fingerprints for evidence.", "test_or_gate": "Pre-publish secret scan gate."},
    {"risk_id": "dist-risk:signing_key_leakage", "category": "security", "severity": "critical", "likelihood": "low", "description": "Code signing private key exposed. Attacker can sign malware as developer identity.", "mitigation": "HSM or hardware token. Keyless signing where possible (OIDC). Never commit private keys.", "test_or_gate": "Certificate fingerprint audit. Key storage audit."},
    {"risk_id": "dist-risk:irreversible_publish", "category": "mutation", "severity": "high", "likelihood": "medium", "description": "Package version published cannot be deleted or modified. npm (72h), PyPI (72h), crates.io (never), App Store (never).", "mitigation": "Dry-run publish to test channel first. Multi-stage approval. SHA check before publish.", "test_or_gate": "Test channel publish succeeded before production."},
    {"risk_id": "dist-risk:malicious_publish", "category": "supply_chain", "severity": "critical", "likelihood": "low", "description": "Compromised CI or credential allows attacker to publish malicious package version.", "mitigation": "OIDC trusted publishers. 2FA enforcement. Sigstore/cosign signing.", "test_or_gate": "Provenance attestation verification. Publish log audit."},
    {"risk_id": "dist-risk:notarization_failure", "category": "signing", "severity": "high", "likelihood": "medium", "description": "macOS notarization fails due to entitlements or malware scan rejection. Gatekeeper blocks app.", "mitigation": "Pre-flight notarization check. Test notarization early in CI.", "test_or_gate": "notarytool submit + status check in CI. spctl -a verify."},
    {"risk_id": "dist-risk:codesigning_failure", "category": "signing", "severity": "high", "likelihood": "medium", "description": "Code signing fails due to expired certificate, wrong provisioning profile, or missing entitlement.", "mitigation": "Monitor certificate expiry with 30-day alerts. Validate signing chain in CI.", "test_or_gate": "codesign -dvvv / signtool verify in CI."},
    {"risk_id": "dist-risk:registry_immutability", "category": "mutation", "severity": "high", "likelihood": "low", "description": "Developer assumes they can delete published package. Cannot. Version permanently burned.", "mitigation": "Document immutability in Rig operating picture. Gate publish with explicit warning.", "test_or_gate": "Registry policy education gate."},
    {"risk_id": "dist-risk:privacy_label_mismatch", "category": "compliance", "severity": "high", "likelihood": "medium", "description": "App privacy nutrition label does not match actual data practices. App Review rejection.", "mitigation": "Generated privacy manifest from code analysis. Pre-submission privacy label check.", "test_or_gate": "Privacy manifest validation gate."},
    {"risk_id": "dist-risk:supply_chain_attestation_gap", "category": "provenance", "severity": "medium", "likelihood": "high", "description": "Release lacks verifiable attestation linking build to source. Fails SLSA Level 1+.", "mitigation": "Generate provenance attestation in CI. sigstore/cosign signing. SBOM.", "test_or_gate": "Provenance attestation verification gate."},
    {"risk_id": "dist-risk:fake_green_tests", "category": "quality", "severity": "high", "likelihood": "medium", "description": "Tests pass but don't cover release-critical paths. False confidence from green CI.", "mitigation": "Release-specific test suite. Integration tests covering distribution paths.", "test_or_gate": "Release-blocking test suite distinct from dev test suite."},
]

ROADMAP = [
    {"phase_id": "dist-roadmap:phase_0_research", "goal": "Research all distribution channels, credentials, APIs, validations, risks.", "mutation_policy": "none", "success_definition": "Rig has a schema-governed research packet for distribution and release governance."},
    {"phase_id": "dist-roadmap:phase_1_operating_picture", "goal": "Distribution Operating Picture: document which channels are configured, safe, or refused.", "mutation_policy": "none", "success_definition": "Cockpit shows honest operating picture of all distribution channels."},
    {"phase_id": "dist-roadmap:phase_2_preflight", "goal": "Release Preflight: run all validation checks without any publish attempt.", "mutation_policy": "none", "success_definition": "Rig can audit release readiness across all channels without mutation."},
    {"phase_id": "dist-roadmap:phase_3_notarization", "goal": "macOS Notarization Captain: submit for notarization, poll status, staple ticket.", "mutation_policy": "approval_required", "success_definition": "Rig can notarize macOS apps with receipt-backed evidence."},
    {"phase_id": "dist-roadmap:phase_4_packages", "goal": "Package Registry Packets: npm, PyPI, crates.io publish in dry-run/approval-required mode.", "mutation_policy": "approval_required", "success_definition": "Rig can publish packages with preflight checks across JS/Python/Rust."},
    {"phase_id": "dist-roadmap:phase_5_github", "goal": "GitHub Release & Pages Operator: create releases, upload assets, deploy Pages.", "mutation_policy": "approval_required", "success_definition": "Rig can manage GitHub Releases and Pages with evidence."},
    {"phase_id": "dist-roadmap:phase_6_app_store", "goal": "App Store & TestFlight Packets: manage TestFlight builds and App Store submissions.", "mutation_policy": "approval_required", "success_definition": "Rig can upload TestFlight builds and submit for review."},
    {"phase_id": "dist-roadmap:phase_7_google_play", "goal": "Google Play Packets: manage tracks, upload bundles, update listings.", "mutation_policy": "approval_required", "success_definition": "Rig can manage Google Play tracks and submissions."},
    {"phase_id": "dist-roadmap:phase_8_microsoft", "goal": "Microsoft Store Packets: manage submissions, package flights, certifications.", "mutation_policy": "approval_required", "success_definition": "Rig can manage Microsoft Store submissions."},
    {"phase_id": "dist-roadmap:phase_9_provenance", "goal": "Provenance, SBOM & Attestation: sign with cosign, generate SBOMs, publish attestations.", "mutation_policy": "automatic_under_policy", "success_definition": "Rig produces SLSA-compliant provenance and SBOMs."},
    {"phase_id": "dist-roadmap:phase_10_mutation", "goal": "Release Mutation Operator: automated publish decisions with approval gates and dry-runs.", "mutation_policy": "approval_required", "success_definition": "Rig can execute publish actions with rollback plans."},
    {"phase_id": "dist-roadmap:phase_11_chief_of_staff", "goal": "Multi-Channel Release Chief of Staff: coordinate releases across all channels.", "mutation_policy": "approval_required", "success_definition": "Rig orchestrates multi-channel releases with unified evidence."},
]

PUBLIC_METADATA = [
    {"metadata_id": "dist-meta:app_name", "channel_ids": ["dist-channel:apple_app_store", "dist-channel:google_play_production", "dist-channel:microsoft_store"], "source_of_truth_candidates": ["Cargo.toml", "package.json", "pyproject.toml", "Xcode project"], "public_claim_risk": "high", "stale_surface_risk": "low", "recommended_rig_policy": "Source-of-truth from canonical metadata file. Cross-check all channels."},
    {"metadata_id": "dist-meta:version", "channel_ids": ["*"], "source_of_truth_candidates": ["git tag", "Cargo.toml", "package.json", "pyproject.toml"], "public_claim_risk": "high", "stale_surface_risk": "high", "recommended_rig_policy": "Single source of truth (git tag or canonical file). Cross-check across all surfaces."},
    {"metadata_id": "dist-meta:release_notes", "channel_ids": ["dist-channel:github_releases", "dist-channel:apple_app_store", "dist-channel:google_play_production"], "source_of_truth_candidates": ["CHANGELOG.md", "RELEASE_NOTES.md"], "public_claim_risk": "medium", "stale_surface_risk": "medium", "recommended_rig_policy": "Prefer single canonical CHANGELOG.md. Auto-copy to store/release."},
    {"metadata_id": "dist-meta:privacy_policy", "channel_ids": ["dist-channel:apple_app_store", "dist-channel:google_play_production", "dist-channel:microsoft_store"], "source_of_truth_candidates": ["PRIVACY.md", "website/docs/privacy"], "public_claim_risk": "critical", "stale_surface_risk": "high", "recommended_rig_policy": "Audit divergence between privacy policy URL and app data practices."},
]

ARTIFACT_CONCEPTS = [
    {"artifact_id": "dist-concept:distribution_operating_picture", "purpose": "Snapshot of which channels are configured, safe, or refused", "content_light_constraints": "No raw credentials. Boolean config flags only.", "mutation_status_fields": ["channel_state (unconfigured/configured/refused/deferred)"]},
    {"artifact_id": "dist-concept:release_channel_inventory", "purpose": "Complete channel matrix with metadata surfaces, risk levels, and support", "content_light_constraints": "Channel metadata only. No real app data.", "mutation_status_fields": []},
    {"artifact_id": "dist-concept:release_credential_ledger", "purpose": "Inventory of all credential/signing/provisioning concepts", "content_light_constraints": "Credential types, storage sensitivity, rotation model. Never raw values.", "mutation_status_fields": []},
    {"artifact_id": "dist-concept:release_preflight_report", "purpose": "Results of all validation checks (pass/fail/warn)", "content_light_constraints": "Check IDs, pass/fail/warn, timestamps. No file contents.", "mutation_status_fields": ["preflight_status (passed/failed/warning)"]},
    {"artifact_id": "dist-concept:release_evidence_bundle", "purpose": "Bundle of preflight evidence, signing receipts, provenance for a release", "content_light_constraints": "Artifact hashes, check results. No raw binaries or source.", "mutation_status_fields": []},
    {"artifact_id": "dist-concept:release_submission_packet", "purpose": "Prepared submission data for store/registry publish", "content_light_constraints": "Metadata, hashes, approval flags. No raw tokens or binaries.", "mutation_status_fields": ["submission_state (draft/ready/submitted/approved/rejected)"]},
    {"artifact_id": "dist-concept:release_mutation_receipt", "purpose": "Proof that a publish/mutation action completed", "content_light_constraints": "Request IDs, timestamps, response summaries, hashes. No raw auth.", "mutation_status_fields": ["mutation_status (success/failed/rolled_back)", "receipt_sha256"]},
]

__all__ = ["APIS", "ARTIFACT_CONCEPTS", "CHANNELS", "CREDENTIALS", "MUTATIONS", "PUBLIC_METADATA", "RISKS", "ROADMAP", "VALIDATIONS"]
